### ISSUE TITLE
DC voting refactor

### ISSUE THREAD

**Issue by schronck** [agoraxyz/discord-runner#167]
## **Improvement**
There has been changes to the guild-backend which altered the voting mechanism. We should update the voting logic in the DC-runner, too.

## **Tasks**
- [x] refactor the voting system according to the updates on the backend
- [x] update bot error messages and voting step descriptions
- [x] remove unused slash commands related to voting
- [x] fix animated emoji reactions
- [x] add requirement-chooser

**Comment by ejayxyz** [comment]
Closed in #175
