### ISSUE TITLE
Poll creation messages

### ISSUE THREAD

**Issue by schronck** [agoraxyz/discord-runner#209]
## Improvement

We should update the messages which are sent to the user during poll creation to make the process easier.

## Tasks

- [x] update messages
- [x] check whether given emojis are valid unicode emojis or Discod emotes
- [x] refactor types as we do not need to store the role in poll objects
- [x] only show the token chooser instead of role & requirement chooser when creating a new poll
- [x] endpoint for getting emoji list from a server `{ name: string, id: string, image: string, animated: boolean }`
